import Foundation

public enum ObcNfoTaskActionEnum: String, Codable, Hashable, CaseIterable, Sendable {
    case cargoBookedWithAirline = "cargo_booked_with_airline"
    case courierAssigned = "courier_assigned"
    case courierEnRouteToPickupLocation = "courier_en_route_to_pickup_location"
    case courierArrivedAtPickupLocation = "courier_arrived_at_pickup_location"
    case cargoPickedUp = "cargo_picked_up"
    case courierEnRouteToAirport = "courier_en_route_to_airport"
    case courierArrivedAtAirport = "courier_arrived_at_airport"
    case ticketPurchased = "ticket_purchased"
    case flightCheckinCompleted = "flight_checkin_completed"
    case courierThruSecurity = "courier_thru_security"
    case cargoAcceptedByAirline = "cargo_accepted_by_airline"
    case courierBoardedFlight1 = "courier_boarded_flight_1"
    case flight1Departed = "flight_1_departed"
    case flight1Arrived = "flight_1_arrived"
    case courierDeboardedFlight1 = "courier_deboarded_flight_1"
    case courierBoardedFlight2 = "courier_boarded_flight_2"
    case flight2Departed = "flight_2_departed"
    case flight2Arrived = "flight_2_arrived"
    case courierDeboardedFlight2 = "courier_deboarded_flight_2"
    case courierBoardedFlight3 = "courier_boarded_flight_3"
    case flight3Departed = "flight_3_departed"
    case flight3Arrived = "flight_3_arrived"
    case courierDeboardedFlight3 = "courier_deboarded_flight_3"
    case courierBoardedFlight4 = "courier_boarded_flight_4"
    case flight4Departed = "flight_4_departed"
    case flight4Arrived = "flight_4_arrived"
    case courierDeboardedFlight4 = "courier_deboarded_flight_4"
    case courierThruCustoms = "courier_thru_customs"
    case courierRecoveredCargo = "courier_recovered_cargo"
    case courierEnRouteToDeliveryLocation = "courier_en_route_to_delivery_location"
    case courierArrivedAtDeliveryLocation = "courier_arrived_at_delivery_location"
    case cargoDelivered = "cargo_delivered"
}